version: '3'

tasks:
  default:
    cmds:
      - task --list

  generate-key-pair:
    desc: Generates a ES256 private and public key pair for the backend
    cmds:
      - openssl ecparam -name prime256v1 -genkey -noout -out private.ec.key
      - openssl ec -in private.ec.key -pubout -out public.pem
      - cat private.ec.key && cat public.pem
      - rm private.ec.key public.pem
